version: "3.9"

services:
  db:
    image: postgres
    container_name: postgres-container
    env_file: .db.env
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - data:/srv/app
    ports:
      - '5432:5432'
      
  api:
    image: mad_rat/ma-api
    container_name: ma-api
    restart: unless-stopped
    env_file: .api.env
    build: ../api/.
    networks:
      - app-network
    # volumes:
    #   - ./.build:/srv/app
    ports:
      - "1337:1337"
networks:
  app-network:
    driver: bridge

volumes:
  data: