version: "3"

services:
  strapi:
    image: strapi/strapi
    container_name: ma-strapi
    restart: unless-stopped
    env_file: .api.env
    networks:
      - app-network
    volumes:
      - ./.app:/srv/app
    ports:
      - "1337:1337"


  api:
    image: eu.gcr.io/ma-100/api
    container_name: ma-api
    build: 
      context: ../api
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .api.env
    networks:
      - app-network
    volumes:
      - ./.app:/srv/app
    ports:
      - "1337:1337"

  pgdatabase:
    image: postgres
    container_name: pgdatabase
    env_file: .pgdatabase.env
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - disk:/data/db
    ports:
      - '5432:5432'

networks:
  app-network:
    driver: bridge

volumes:
  disk: